Repository redhat-developer/intellij-quarkus, pull requests merged in 2023-12, with the labels that each got.

#1284 chore: add gradle wrapper validation
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: build

#1288 feat: Declare server icon with icon attribute
  src/main/java/com/redhat/devtools/intellij/microprofile/lang/MicroProfileServerIconProvider.java
  src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusIconProvider.java
  src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusIcons.java
  src/main/java/com/redhat/devtools/intellij/quarkus/lang/QuarkusServerIconProvider.java
  src/main/java/com/redhat/devtools/intellij/qute/lang/QuteLanguageSubstitutor.java
  src/main/resources/META-INF/lsp4ij-quarkus.xml
  src/main/resources/META-INF/lsp4ij-qute.xml
Labels: enhancement

#1287 build: fetch latest nightly LSP4IJ version
  build.gradle.kts
Labels: build

#1292 feat: remove LSP codeLens/inlahint declaration by using inlay hint factory
  src/main/resources/META-INF/lsp4ij-quarkus.xml
  src/main/resources/META-INF/lsp4ij-qute.xml
Labels: enhancement

#1297 fix: use JSONUtils from LSP4IJ
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/MicroProfileConfigConstants.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileOpenURIAction.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/command/MicroprofileUpdateConfigurationAction.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/MicroProfileConfigASTValidator.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/NoValueAssignedToPropertyQuickFix.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/config/java/PropertyNameData.java
  src/main/java/com/redhat/devtools/intellij/quarkus/lsp/QuarkusLanguageClient.java
  src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteAction.java
  src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteGenerateTemplateAction.java
  src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteJavaDefinitionAction.java
  src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteOpenURIAction.java
  src/main/java/com/redhat/devtools/intellij/qute/psi/core/command/QuteUpdateConfigurationAction.java
Labels: bug

#1298 build: replace remark with flexmark
  build.gradle.kts
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/core/ls/PsiUtilsLSImpl.java
  src/main/java/com/redhat/devtools/intellij/quarkus/javadoc/JavaDoc2MarkdownConverter.java
  src/main/java/com/redhat/microprofile/psi/internal/quarkus/kubernetes/properties/QuarkusKubernetesProvider.java
  src/test/java/com/redhat/devtools/intellij/qute/psi/template/TemplateGetJavadocTest.java
  src/test/java/com/redhat/microprofile/psi/quarkus/QuarkusKubernetesTest.java
Labels: build
