Repository redhat-developer/intellij-quarkus, pull requests merged in 2024-05, with the labels that each got.

#1327 fix: prevent IJ from reporting an error when config file is deleted
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
Labels: bug

#1326 fix: properly validate variables with default values in @Scheduled field
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/PropertiesManagerForJava.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/hover/PropertiesHoverParticipant.java
  src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/SchedulerErrorCodes.java
  src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/SchedulerUtils.java
  src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/java/QuarkusSchedulerASTVisitor.java
  src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/properties/QuarkusScheduledPropertiesProvider.java
  src/test/java/com/redhat/microprofile/psi/quarkus/scheduler/SchedulerUtilsTest.java
Labels: quarkus, completion, validation, hover

#1275 feat: More checks for return types from GraphQL operations
  projects/lsp4mp/projects/maven/microprofile-graphql/pom.xml
  projects/lsp4mp/projects/maven/microprofile-graphql/src/main/java/io/openliberty/graphql/sample/WeatherService.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/MicroProfileGraphQLConstants.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLASTValidator.java
  src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/internal/graphql/java/MicroProfileGraphQLErrorCode.java
  src/test/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/graphql/java/MicroProfileGraphQLValidationTest.java
Labels: enhancement, quarkus

#1334 refactor: use ProjectActivity API
  src/main/java/com/redhat/devtools/intellij/quarkus/QuarkusPostStartupActivity.java
Labels: refactor
